## Extracao dos dados

In [60]:
import pandas as pd
pd.set_option("display.max_columns", None)

dataframe_de_churn_inicial = pd.read_csv("C:\\Projetos\\FIAP\\Fase_1\\Tech_Challenge_Churn_Prediction\\data\\raw\\Telco-Customer-Churn.csv", sep=",")

dataframe_de_churn_inicial.head(n=100)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8637-XJIVR,Female,0,No,No,12,Yes,Yes,Fiber optic,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,78.95,927.35,Yes
96,9803-FTJCG,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,One year,Yes,Credit card (automatic),66.85,4748.7,No
97,0278-YXOOG,Male,0,No,No,5,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,21.05,113.85,Yes
98,3212-KXOCR,Male,0,No,No,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),21.00,1107.2,No
99,4598-XLKNJ,Female,1,Yes,No,25,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.50,2514.5,Yes

## Transformacao de nomes de features para portugues

In [61]:
colunas_pt_br = {
    "customerID": "id_cliente",
    "gender": "genero",
    "SeniorCitizen": "cliente_em_idade_avancada",
    "Partner": "casado",
    "Dependents": "dependentes",
    "tenure": "meses_como_cliente",
    "PhoneService": "possui_servico_telefonico",
    "MultipleLines": "possui_multiplas_linhas",
    "InternetService": "possui_servico_de_internet",
    "OnlineSecurity": "possui_seguranca_online",
    "OnlineBackup": "possui_backup_online",
    "DeviceProtection": "possui_protecao_dispositivo",
    "TechSupport": "possui_suporte_tecnico_premium",
    "StreamingTV": "possui_streaming_tv_terceiros",
    "StreamingMovies": "possui_streaming_filmes_terceiros",
    "Contract": "tipo_contrato",
    "PaperlessBilling": "fatura_sem_papel",
    "PaymentMethod": "metodo_pagamento",
    "MonthlyCharges": "cobranca_mensal",
    "TotalCharges": "total_cobrado_durante_trimestre",
    "Churn": "target",
}

dataframe_de_churn_inicial_colunas_traduzidas = dataframe_de_churn_inicial.rename(columns=colunas_pt_br)

dataframe_de_churn_inicial_colunas_traduzidas.head(n=100)

,id_cliente,genero,cliente_em_idade_avancada,casado,dependentes,meses_como_cliente,possui_servico_telefonico,possui_multiplas_linhas,possui_servico_de_internet,possui_seguranca_online,possui_backup_online,possui_protecao_dispositivo,possui_suporte_tecnico_premium,possui_streaming_tv_terceiros,possui_streaming_filmes_terceiros,tipo_contrato,fatura_sem_papel,metodo_pagamento,cobranca_mensal,total_cobrado_durante_trimestre,target
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8637-XJIVR,Female,0,No,No,12,Yes,Yes,Fiber optic,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,78.95,927.35,Yes
96,9803-FTJCG,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,One year,Yes,Credit card (automatic),66.85,4748.7,No
97,0278-YXOOG,Male,0,No,No,5,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,21.05,113.85,Yes
98,3212-KXOCR,Male,0,No,No,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),21.00,1107.2,No
99,4598-XLKNJ,Female,1,Yes,No,25,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.50,2514.5,Yes

## Mudanca da variavel target para binaria

In [62]:
dataframe_de_churn_inicial_colunas_traduzidas["target"] = dataframe_de_churn_inicial_colunas_traduzidas["target"].map({"Yes": 1, "No": 0})

dataframe_de_churn_inicial_colunas_traduzidas.head(n=100)

,id_cliente,genero,cliente_em_idade_avancada,casado,dependentes,meses_como_cliente,possui_servico_telefonico,possui_multiplas_linhas,possui_servico_de_internet,possui_seguranca_online,possui_backup_online,possui_protecao_dispositivo,possui_suporte_tecnico_premium,possui_streaming_tv_terceiros,possui_streaming_filmes_terceiros,tipo_contrato,fatura_sem_papel,metodo_pagamento,cobranca_mensal,total_cobrado_durante_trimestre,target
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8637-XJIVR,Female,0,No,No,12,Yes,Yes,Fiber optic,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,78.95,927.35,1
96,9803-FTJCG,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,One year,Yes,Credit card (automatic),66.85,4748.7,0
97,0278-YXOOG,Male,0,No,No,5,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,21.05,113.85,1
98,3212-KXOCR,Male,0,No,No,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),21.00,1107.2,0
99,4598-XLKNJ,Female,1,Yes,No,25,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.50,2514.5,1

## Removendo features sensiveis

In [63]:
colunas_sensiveis_sem_relevancia_para_churn = ["id_cliente", "genero", "dependentes"]

dataframe_de_churn_inicial_colunas_sensiveis_removidas = dataframe_de_churn_inicial_colunas_traduzidas.drop(columns=colunas_sensiveis_sem_relevancia_para_churn)

dataframe_de_churn_inicial_colunas_sensiveis_removidas.head(n=100)

,cliente_em_idade_avancada,casado,meses_como_cliente,possui_servico_telefonico,possui_multiplas_linhas,possui_servico_de_internet,possui_seguranca_online,possui_backup_online,possui_protecao_dispositivo,possui_suporte_tecnico_premium,possui_streaming_tv_terceiros,possui_streaming_filmes_terceiros,tipo_contrato,fatura_sem_papel,metodo_pagamento,cobranca_mensal,total_cobrado_durante_trimestre,target
0,0,Yes,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,0,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,0,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,0,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,0,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,No,12,Yes,Yes,Fiber optic,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,78.95,927.35,1
96,0,Yes,71,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,One year,Yes,Credit card (automatic),66.85,4748.7,0
97,0,No,5,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,21.05,113.85,1
98,0,No,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),21.00,1107.2,0
99,1,Yes,25,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.50,2514.5,1

## Binarizando features categoricas deterministicas

In [64]:
dataframe_de_churn_inicial_colunas_sensiveis_removidas["casado"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["casado"].map({"Yes": 1, "No": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["fatura_sem_papel"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["fatura_sem_papel"].map({"Yes": 1, "No": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_servico_telefonico"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_servico_telefonico"].map({"Yes": 1, "No": 0})

dataframe_de_churn_inicial_colunas_sensiveis_removidas.head(n=100)

,cliente_em_idade_avancada,casado,meses_como_cliente,possui_servico_telefonico,possui_multiplas_linhas,possui_servico_de_internet,possui_seguranca_online,possui_backup_online,possui_protecao_dispositivo,possui_suporte_tecnico_premium,possui_streaming_tv_terceiros,possui_streaming_filmes_terceiros,tipo_contrato,fatura_sem_papel,metodo_pagamento,cobranca_mensal,total_cobrado_durante_trimestre,target
0,0,1,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0
2,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,12,1,Yes,Fiber optic,Yes,No,No,No,No,No,Month-to-month,1,Electronic check,78.95,927.35,1
96,0,1,71,1,Yes,DSL,Yes,Yes,No,Yes,No,No,One year,1,Credit card (automatic),66.85,4748.7,0
97,0,0,5,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,0,Mailed check,21.05,113.85,1
98,0,0,52,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,0,Bank transfer (automatic),21.00,1107.2,0
99,1,1,25,1,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,1,Electronic check,98.50,2514.5,1

## Trabalhando com features binarias nao determinitiscas

In [65]:
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_seguranca_online"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_seguranca_online"].map({"Yes": 1, "No": 0, "No internet service": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_backup_online"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_backup_online"].map({"Yes": 1, "No": 0, "No internet service": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_protecao_dispositivo"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_protecao_dispositivo"].map({"Yes": 1, "No": 0, "No internet service": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_suporte_tecnico_premium"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_suporte_tecnico_premium"].map({"Yes": 1, "No": 0, "No internet service": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_streaming_tv_terceiros"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_streaming_tv_terceiros"].map({"Yes": 1, "No": 0, "No internet service": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_streaming_filmes_terceiros"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_streaming_filmes_terceiros"].map({"Yes": 1, "No": 0, "No internet service": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_multiplas_linhas"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_multiplas_linhas"].map({"Yes": 1, "No": 0, "No phone service": 0})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_servico_de_internet"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["possui_servico_de_internet"].map({"No": 0, "Fiber optic": 1, "DSL": 2})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["tipo_contrato"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["tipo_contrato"].map({"Month-to-month": 0, "One year": 1, "Two year": 2})
dataframe_de_churn_inicial_colunas_sensiveis_removidas["metodo_pagamento"] = dataframe_de_churn_inicial_colunas_sensiveis_removidas["metodo_pagamento"].map({"Mailed check": 0, "Electronic check": 1, "Bank transfer (automatic)": 2, "Credit card (automatic)": 3})

dataframe_de_churn_inicial_colunas_sensiveis_removidas.head(n=100)

,cliente_em_idade_avancada,casado,meses_como_cliente,possui_servico_telefonico,possui_multiplas_linhas,possui_servico_de_internet,possui_seguranca_online,possui_backup_online,possui_protecao_dispositivo,possui_suporte_tecnico_premium,possui_streaming_tv_terceiros,possui_streaming_filmes_terceiros,tipo_contrato,fatura_sem_papel,metodo_pagamento,cobranca_mensal,total_cobrado_durante_trimestre,target
0,0,1,1,0,0,2,0,1,0,0,0,0,0,1,1,29.85,29.85,0
1,0,0,34,1,0,2,1,0,1,0,0,0,1,0,0,56.95,1889.5,0
2,0,0,2,1,0,2,1,1,0,0,0,0,0,1,0,53.85,108.15,1
3,0,0,45,0,0,2,1,0,1,1,0,0,1,0,2,42.30,1840.75,0
4,0,0,2,1,0,1,0,0,0,0,0,0,0,1,1,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,12,1,1,1,1,0,0,0,0,0,0,1,1,78.95,927.35,1
96,0,1,71,1,1,2,1,1,0,1,0,0,1,1,3,66.85,4748.7,0
97,0,0,5,1,0,0,0,0,0,0,0,0,0,0,0,21.05,113.85,1
98,0,0,52,1,0,0,0,0,0,0,0,0,2,0,2,21.00,1107.2,0
99,1,1,25,1,0,1,0,1,1,0,1,1,0,1,1,98.50,2514.5,1

## Informacoes estruturais

In [66]:
dataframe_de_churn_inicial_colunas_sensiveis_removidas.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   cliente_em_idade_avancada          7043 non-null   int64
 1   casado                             7043 non-null   int64
 2   meses_como_cliente                 7043 non-null   int64
 3   possui_servico_telefonico          7043 non-null   int64
 4   possui_multiplas_linhas            7043 non-null   int64
 5   possui_servico_de_internet         7043 non-null   int64
 6   possui_seguranca_online            7043 non-null   int64
 7   possui_backup_online               7043 non-null   int64
 8   possui_protecao_dispositivo        7043 non-null   int64
 9   possui_suporte_tecnico_premium     7043 non-null   int64
 10  possui_streaming_tv_terceiros      7043 non-null   int64
 11  possui_streaming_filmes_terceiros  7043 non-null   int64
 12  tipo_contrato                      7043 non-null   int64
 13  fatura_sem_papel                   7043 non-null   int64
 14  metodo_pagamento                   7043 non-null   int64
 15  cobranca_mensal                    7043 non-null   float64
 16  total_cobrado_durante_trimestre    7043 non-null   str
 17  target                             7043 non-null   int64
dtypes: float64(1), int64(16), str(1)
memory usage: 990.6 KB

## Identificando Missing Values

In [69]:
print(dataframe_de_churn_inicial_colunas_sensiveis_removidas.isna().sum())
dataframe_validacao_cenario_meses_como_cliente_zero = dataframe_de_churn_inicial_colunas_sensiveis_removidas[
    (dataframe_de_churn_inicial_colunas_sensiveis_removidas["meses_como_cliente"].isna())
    | (dataframe_de_churn_inicial_colunas_sensiveis_removidas["meses_como_cliente"] == 0)]
dataframe_validacao_cenario_meses_como_cliente_zero.head(n=100)

cliente_em_idade_avancada            0
casado                               0
meses_como_cliente                   0
possui_servico_telefonico            0
possui_multiplas_linhas              0
possui_servico_de_internet           0
possui_seguranca_online              0
possui_backup_online                 0
possui_protecao_dispositivo          0
possui_suporte_tecnico_premium       0
possui_streaming_tv_terceiros        0
possui_streaming_filmes_terceiros    0
tipo_contrato                        0
fatura_sem_papel                     0
metodo_pagamento                     0
cobranca_mensal                      0
total_cobrado_durante_trimestre      0
target                               0
dtype: int64

,cliente_em_idade_avancada,casado,meses_como_cliente,possui_servico_telefonico,possui_multiplas_linhas,possui_servico_de_internet,possui_seguranca_online,possui_backup_online,possui_protecao_dispositivo,possui_suporte_tecnico_premium,possui_streaming_tv_terceiros,possui_streaming_filmes_terceiros,tipo_contrato,fatura_sem_papel,metodo_pagamento,cobranca_mensal,total_cobrado_durante_trimestre,target
488,0,1,0,0,0,2,1,0,1,1,1,0,2,1,2,52.55,,0
753,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,20.25,,0
936,0,1,0,1,0,2,1,1,1,0,1,1,2,0,0,80.85,,0
1082,0,1,0,1,1,0,0,0,0,0,0,0,2,0,0,25.75,,0
1340,0,1,0,0,0,2,1,1,1,1,1,0,2,0,3,56.05,,0
3331,0,1,0,1,0,0,0,0,0,0,0,0,2,0,0,19.85,,0
3826,0,1,0,1,1,0,0,0,0,0,0,0,2,0,0,25.35,,0
4380,0,1,0,1,0,0,0,0,0,0,0,0,2,0,0,20.00,,0
5218,0,1,0,1,0,0,0,0,0,0,0,0,1,1,0,19.70,,0
6670,0,1,0,1,1,2,0,1,1,1,1,0,2,0,0,73.35,,0
6754,0,0,0,1,1,2,1,1,0,1,0,0,2,1,2,61.90,,0

## Removendo os Missing Values

In [ ]:
meses_como_cliente_igual_a_zero = dataframe_de_churn_inicial_colunas_sensiveis_removidas["meses_como_cliente"] == 0
total_cobrado_numerico = pd.to_numeric(dataframe_de_churn_inicial_colunas_sensiveis_removidas["total_cobrado_durante_trimestre"], errors="coerce")
total_cobrado_nulo_vazio_ou_zero = total_cobrado_numerico.isna() | (total_cobrado_numerico == 0)

dataframe_de_churn_inicial_colunas_sensiveis_removidas = dataframe_de_churn_inicial_colunas_sensiveis_removidas[
    ~(meses_como_cliente_igual_a_zero & total_cobrado_nulo_vazio_ou_zero)
]

dataframe_de_churn_inicial_colunas_sensiveis_removidas.head(n=100)

## Informacoes Estatisticas